#write docker-compose.yml for GoCD server and agent and tomcat-server 1.8
---

version: '2.1'
services:
  gocd-server:
    image: gocd/gocd-server:v22.3.0
    container_name: gocd-server
    environment:
      - GO_SERVER_SYSTEM_PROPERTIES=-Dgo.console.stdout=true
      - GO_SERVER_PORT=8153
      - GO_SERVER_SSL_PORT=8154
    volumes:
      - ./data/config:/godata/config
      - ./data/artifacts:/godata/artifacts
      - ./data/plugins:/godata/plugins
      - ./data/logs:/godata/logs
    ports:
      - 8153:8153
      - 8154:8154
    networks:
      - gocd-network
  gocd-agent:
    image: gocd/gocd-agent-alpine-3.15:v22.3.0
    container_name: gocd-agent
    environment:
      - GO_SERVER_URL=http://172.20.10.3:8153/go
      - AGENT_KEY=123456789
    volumes:
      - ./data/agent-config:/godata/config
      - ./data/agent-artifacts:/godata/artifacts
      - ./data/agent-plugins:/godata/plugins
      - ./data/agent-logs:/godata/logs
    networks:
      - gocd-network
  tomcat-server:
    image: tomcat:8.5.69-jdk8-openjdk
    container_name: tomcat-server
    ports:
      - 8080:8080
      - 8009:8009
      - 8443:8443
    volumes:
      - ./data/tomcat-server/webapps:/usr/local/tomcat/webapps
      - ./data/tomcat-server/conf:/usr/local/tomcat/conf
       - ./data/tomcat-server/logs:/usr/local/tomcat/logs

networks:
  gocd-network:
    driver: bridge

