#write a GoCD pipeline to clean, package a spring boot application existing with this template under the folder src/.. in a git repository  and finally deoloy to tomcat server runing in docker container
format_version: 10
pipelines:
  pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a5b18f4:
        git: https://github.com/mehdi1-3/gocd
        shallow_clone: false
        auto_update: true
        branch: master

    stages:
      - build:
          jobs:
            hello:
              tasks:
                - exec:
                    command: env