#write a GoCD pipeline to clean, package a spring boot application existing with this template under the folder src/.. in a git repository  and finally deoloy to tomcat server runing in docker container
format_version: 10
pipelines:
  pipeline:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    materials:
      git:
        auto_update: true
        branch: master
        destination: pipeline
        filter:
          ignore:
          - .gitignore
        name: pipeline
        shallow_clone: false
        url: https://github.com/mehdi1-3/gocd

    stages:
    - clean:
        clean:
          working_directory: src/main/java/com/mehdi/SpringBootRestWithH2
          command: mvn clean
        jobs:
        - clean:
            tasks:
            - exec:
                command: mvn clean
                working_directory: src/main/java/com/mehdi/SpringBootRestWithH2
    - package:
        package:
          working_directory: src/main/java/com/mehdi/SpringBootRestWithH2
          command: mvn package
        jobs:
        - package:
            tasks:
            - exec:
                command: mvn package
                working_directory: src/main/java/com/mehdi/SpringBootRestWithH2
    - deploytomcat:
        deploytomcat:
          working_directory: src/main/java/com/mehdi/SpringBootRestWithH2
          command: mvn deploytomcat
        jobs:
        - deploytomcat:
            tasks:
            - exec:
                command: mvn deploytomcat
                working_directory: src/main/java/com/mehdi/SpringBootRestWithH2







