#write a GoCD pipeline to clean, package a spring boot application existing with this template under the folder src/.. in a git repository  and finally deoloy to tomcat server runing in docker container
format_version: 10
pipelines:
  provisioning:
    group: ops
    materials:
      provisioning:
        git: 'https://github.com/mehdi1-3/gocd'
    stages:
      - build:
          jobs:
            hello:
              tasks:
                - exec:
                    command: env







