format_version: 10
pipelines:
  pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-cb27d0d:
        git: https://github.com/mehdi1-3/gocd
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - clean:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            clean:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - clean
                    command: mvn
                    run_if: passed